### ISSUE TITLE
TypeError: i.toSorted is not a function

### ISSUE THREAD

**Issue by CheloXL** [samthor/kuto#2]
I'm trying kuto on my bundle and I'm getting the following error: 
```
TypeError: i.toSorted is not a function
    at Is (file:///e:/ExtremeFX/ReFit/RefitApp/RefitApi/node_modules/kuto/dist/app.kt-00TyR2X.js:1:14010)
    at al.build (file:///e:/ExtremeFX/ReFit/RefitApp/RefitApi/node_modules/kuto/dist/app.kt-00TyR2X.js:15:8672)
    at Ws (file:///e:/ExtremeFX/ReFit/RefitApp/RefitApi/node_modules/kuto/dist/app.kt-00TyR2X.js:1:20614)
```
Node.js v18.17.1

**Comment by CheloXL** [comment]
Just upgraded and I'm still getting the same error.

**Comment by CheloXL** [comment]
Ok, I can confirm it was Node. Just upgraded to 20.11.1 and everything seems to work (at least no errors and output was created).
